### ISSUE TITLE
missing the config file 

### ISSUE THREAD

**Issue by xinxiaozhe12345** [cvlab-stonybrook/HandLer#1]
Hi, thanks for your great work on hand tracking. I am so interested in your work and want to run inference on my custom videos, but find the config file yt_trk.yaml is missing. When would you will share the config file, looking forward to your reply.

**Comment by Mingzhen-Huang** [comment]
Hi @xinxiaozhe12345 Please find the [config file](https://github.com/cvlab-stonybrook/HandLer/blob/master/projects/HandLer/configs/yt_trk.yaml) here.
