### ISSUE TITLE
Youtube-Hands Dataset does not contain pose_hm 

### ISSUE THREAD

**Issue by Matus-Tanonwong** [cvlab-stonybrook/HandLer#2]
Hello, there!! 
Thank you very much for your great work. It is very interesting.
I have one question about Youtube-Hands dataset. 
When I try training the model on Youtube-Hands dataset, I receive an error saying **"No such file or directory: /Youtube-Hands/pose_hm/train/kids_playing_v11/img1/frame000556.npy"**
Could you please guide me where I can find such file?
Thank you very much in advance for your consideration.

## 📚 Documentation

* Links to the relevant documentation/comment:

**Comment by h-ccc** [comment]
I also ran into this problem, do you solve it? Can you tell me how you solved it. Thanks in advance.

**Comment by Matus-Tanonwong** [comment]
Hi, I still cannot solve this issue. I'm sorry @h-ccc

**Comment by h-ccc** [comment]
It's okay, thank you very much again for your prompt reply

**Comment by h-ccc** [comment]
I removed the code about the `pre_hm_path`. It allows training without this part of the data, but I don't know if it will affect the final performance

**Comment by Mingzhen-Huang** [comment]
Hi, the pose_hm is the pose heatmap from a pretrained pose estimation method, feel free to generate it with any pose estimation method you like (e.g., openpose). You can also find the generated pose heatmap here: https://drive.google.com/file/d/1BBepIVJNAo_dW7IX5ZBy6KxTODWupNth/view?usp=sharing
